// Authorization
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Invoices
export const INVOICES_FETCHING = 'INVOICES_FETCHING';
export const INVOICE_CREATE = 'INVOICE_CREATE';
export const INVOICE_EDIT = 'INVOICE_EDIT';
export const INVOICE_DELETE = 'INVOICE_DELETE';

// Products
export const PRODUCTS_FETCHING = 'PRODUCTS_FETCHING';
export const PRODUCT_CREATE = 'PRODUCT_CREATE';
export const PRODUCT_EDIT = 'PRODUCT_EDIT';
export const PRODUCT_DELETE = 'PRODUCT_DELETE';

// Customers
export const CUSTOMERS_FETCHING = 'CUSTOMERS_FETCHING';
export const CUSTOMER_CREATE = 'CUSTOMER_CREATE';
export const CUSTOMER_EDIT = 'CUSTOMER_EDIT';
export const CUSTOMER_DELETE = 'CUSTOMER_DELETE';

// Loading
export const LOADING_START = 'LOADING_START';
export const LOADING_FINISH = 'LOADING_FINISH';